# Generated by Django 5.1.2 on 2024-11-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone', models.IntegerField()),
                ('subject', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cname',
            new_name='name',
        ),
    ]
